

#' Discrete colour scales for ggplot2
#'
#
#' @description Discrete ggplot2 color scales using the color palettes generated by ricky
#'
#' @details
#' \describe{
#' \item{direction}{= 1 is preface the palette colour, = -1 is reverse order the palette colour}
#' \item{primary}{The primary colour}
#' \item{other}{The other colour}
#
#'
#' @examples
#' # plot with discrete scale gg + scale_colour_ricky_d()
scale_colour_ricky_d <- function(direction = 1, primary = "yellow",
                                other = "green",...) {
  ggplot2::discrete_scale( "colour", "ricky",
                           ricky_palette(primary, other, direction),
    ...
  )
}

#' Discrete fill scales for ggplot2
#' @description Discrete ggplot2 fill scales using the color palettes generated by ricky
#'
#' @details
#' \describe{
#' \item{direction}{= 1 is preface the palette colour, = -1 is reverse order the palette colour}
#' \item{primary}{The primary colour}
#' \item{other}{The other colour}
#
#'
#' @examples
#' # plot with discrete scale gg + scale_fill_ricky_d()
scale_fill_ricky_d <- function(direction = 1, primary = "blue",
                               other = "green",...) {
  ggplot2::discrete_scale( "fill", "ricky",
                           ricky_palette(primary, other, direction),
    ...
  )
}
