

ricky_colours <- list(
  "pink" = "#ff7aa2",
  "blue" = "#07a0c3",
  "red"  = "#ea3546",
  "yellow" = "#FAFA61",
  "green"  = "#80ed99",
  "navy"   = "#2e4057",
  "grey"   = "#e0e0e2"
)


#' Palette
#'
#' @description The color palettes generated by ricky.
#' @details {
#' \item{primary}{The primary colour}
#' \item{other}{The other colour}
#' \item{direction}{= 1 is preface the palette colour, = -1 is reverse order the palette colour}
#' \item{n}{The number of colour select}
#
#'
#' @examples
#' # ricky_palette(direction = 1)(2)
ricky_palette <- function(
  primary = "yellow",
  other = "blue",
  direction = 1) {
  stopifnot(primary %in% names(ricky_colours))

  function(n) {
    if (n > 7) warning("Ricky Colour Palette only has 7 colors.")

    if (n < 1) warning("You must select at least 1 colour.")

    if (n == 2) {
      other <- if (!other %in% names(ricky_colours)) {
        other
      } else {
        ricky_colours[other]
      }
      colour_list <- c(other, ricky_colours[primary])
    } else {
      colour_list <- ricky_colours[1:n]
    }

    colour_list <- unname(unlist(colour_list))
    if (direction >= 0) colour_list else rev(colour_list)
  }
}

